tango_with_django_project/rango/urls.py
from django.conf.urls import url

from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from rango import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # Any URLs starting 'rango/' will be handled by the rango application.
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    # Links UserProfile to the User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __str__() method to return out something meaningful.
    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User

from rango.models import Category, Page, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category's name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and the Model.
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=128,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and the Model.
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some field may allow NULL values, so we may wish to exclude them.
        # Here we are hiding the ForeignKey.
        exclude = ('category',)
        # Alternatively we could specific the fields to input
        # i.e. fields = ('title', 'url', 'views',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and does not begin with 'http://'
        # prepend 'http://'
        if url and not url.startswith('http://'):
            url = "http://" + url
            cleaned_data['url'] = url

            return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'emails', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django_project/rango/views.py
from django.shortcuts import render
from django.http import HttpResponse

from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm

def index(request):
    # Query the database for a list of all categories stored.
    # Order the categories by the number of likes in descending order.
    # Retrieve up to the top five categories.
    # Place the list in our context dictionary that will be passed to our
    # template engine.
    context_dict = {}
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    # Render the response and send it back.
    return render(request, 'rango/index.html', context=context_dict)

def about(request):
    context_dict = {'author_name': "Adam Joyce"}
    return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):
    # Context dictionary to pass to the template render engine.
    context_dict = {}

    try:
        # Is there a category name slug with the given name?
        # If not, the .get() method raises a DoesNotExist exception.
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve all associated pages.
        pages = Page.objects.filter(category=category)

        # Add the results to the template context under the name 'pages'.
        context_dict['pages'] = pages

        # Add the category object to the context for use in the template.
        # It will determine if the category exits.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # The template will display no catgeory.
        context_dict['category'] = None
        context_dict['pages'] = None

    # Render the response and return it to the client.
    return render(request, 'rango/category.html', context_dict)

def add_category(request):
    form = CategoryForm()

    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)
            # Could provide a confirmation message but for this project
            # the category will be added to the index page.
            # Redirect the user to the index page.
            return index(request)
        else:
            # The supplied form contains errors.
            print(form.errors)

    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages if any.
    return render(request, 'rango/add_category.html', {'form': form})

def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form':form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
About
{% endblock %}

{% block body_block %}
<h1>About Page</h1>

<div>
  <p>This tutorial has been put together by {{ author_name }}.</p>
</div>

<div>
  <img src="{{ MEDIA_URL }}cat.jpg" alt="Cat Picture">
</div>
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title_block %}
About
{% endblock %}

{% block body_block %}
<h1>Add a Category</h1>

<div>
  <form id="category_form" action="{% url 'rango:add_category' %}" method="post">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}
    {{ field }}
    {% endfor %}
    <input type="submit" name="submit" value="Create Category">
  </form>
</div>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title_block %}
About
{% endblock %}

{% block body_block %}
<h1>Add a Page</h1>

<div>
  {% if category %}
  <form id="page_form"
  action="{% url 'rango:add_page' category.slug %}" method="post">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}
    {{ field }}
    {% endfor %}
    <input type="submit" name="submit" value="Create Category">
  </form>
  {% else %}
  <p>The specified category does not exist!</p>
  {% endif %}
</div>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load rango_template_tags %}

<html>
  <head lang="en">
    <meta charset="utf-8">
    <title>
      Rango -
      {% block title_block %}
      How to Tango with Django!
      {% endblock %}
    </title>
  </head>
  <body>
    <div>
      {% block sidebar_block %}
      {% get_category_list category %}
      {% endblock %}

      {% block body_block %}
      {% endblock %}
    </div>

    <hr>

    <div>
      <ul>
        <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
      </ul>
    </div>
  </body>
</html>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
{{ category.name }}
{% endblock %}

{% block body_block %}
{% if category %}
<h1>{{ category.name }}</h1>

{% if pages %}
<ul>
  {% for page in pages %}
  <li><a href="{{ page.url }}">{{ page.title }}</a></li>
  {% endfor %}
</ul>
{% else %}
<strong>No pages currently in category.</strong><br>
{% endif %}
<a href="{% url 'rango:add_page' category.slug %}">Add Page</a>
{% else %}
<p>The specified category does not exist!</p>
{% endif %}
{% endblock %}

tango_with_django_project/templates/rango/cats.html
<ul>
  {% for c in cats %}
  {% if c == act_cat %}
  <li>
    <strong>
      <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
    </strong>
  </li>
  {% else %}
  <li>
    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
  </li>
  {% endif %}
  {% endfor %}
</ul>

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Home
{% endblock %}

{% block body_block %}
<div>
  <h2>Most Liked Categories</h2>
  {% if categories %}
  <ul>
    {% for category in categories %}
    <li><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <strong>There are no categories present.</strong>
  {% endif %}
</div>

<div>
  <h2>Most Viewed Pages</h2>
  {% if pages %}
  <ul>
    {% for page in pages %}
    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <strong>There are no pages present.</strong>
  {% endif %}
</div>

<div>
  <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango">
</div>
{% endblock %}